words_for_day_7 = [
    'Apple', 'House', 'River', 'Chair', 'Light', 'Window', 'Jungle', 'Ocean', 'Guitar', 'Rabbit',
    'Quizzes', 'Oxygen', 'Galaxy', 'Knight', 'Pyramid', 'Zephyr', 'Xylophone', 'Euphoria', 'Rhythm', 'Sphinx',
    'Banana', 'Mountain', 'Festival', 'Elephant', 'Diamond', 'Tornado', 'Whisper', 'Glacier', 'Falcon', 'Laptop',
    'Village', 'Scorpion', 'Adventure', 'Museum', 'Library', 'Universe', 'Computer', 'Rainbow', 'Coconut', 'Phantom',
    'Horizon', 'Phoenix', 'Satellite', 'Volcano', 'Bicycle', 'Mystery', 'Alphabet', 'Butterfly', 'Chocolate', 'Puzzle',
    'Mushroom', 'Caravan', 'Courage', 'Dragonfly', 'Electricity', 'Treasure', 'Zebra', 'Astronomy', 'Boulevard', 'Cryptic',
    'Eclipse', 'Fountain', 'Harmony', 'Immortal', 'Jazz', 'Kangaroo', 'Labyrinth', 'Nebula', 'Oracle', 'Paradox',
    'Quantum', 'Radiance', 'Spectrum', 'Tsunami', 'Umbrella', 'Voyage', 'Wilderness', 'Xenon', 'Yacht', 'Zodiac',
    'Ancient', 'Behemoth', 'Cathedral', 'Dystopia', 'Ecosystem', 'Fossil', 'Gladiator', 'Hexagon', 'Illusion', 'Jubilee',
    'Kryptonite', 'Labyrinthine', 'Mandolin', 'Nebulizer', 'Obsidian', 'Palindrome', 'Quasar', 'Renaissance', 'Symphony', 'Typhoon',
    'Ultraviolet', 'Vortex', 'Wavelength', 'Xenophobia', 'Yogurt', 'Zeppelin', 'Berserk', 'Cascade', 'Desolate', 'Ephemeral',
    'Fractal', 'Gargoyle', 'Helix', 'Infinity', 'Jigsaw', 'Kilometer', 'Luminous', 'Monolith', 'Nucleus', 'Oblivion',
    'Pyramid', 'Quagmire', 'Resonance', 'Silhouette', 'Tesseract', 'Utopia', 'Vigilante', 'Whirlpool', 'Xylophone', 'Yonder',
    'Zoology', 'Aurora', 'Blizzard', 'Crescent', 'Dragon', 'Equinox', 'Flamingo', 'Geyser', 'Hologram', 'Icicle',
    'Jaguar', 'Kaleidoscope', 'Lantern', 'Meteor', 'Nautilus', 'Oasis', 'Phoenix', 'Quartz', 'Raspberry', 'Sapphire',
    'Tundra', 'Universe', 'Vampire', 'Waterfall', 'Xerox', 'Yeti', 'Zenith', 'Arcade', 'Balloon', 'Canyon',
    'Dolphin', 'Empire', 'Feather', 'Galaxy', 'Hurricane', 'Igloo', 'Jungle', 'Kite', 'Lighthouse', 'Mermaid',
    'Nebula', 'Ocelot', 'Pegasus', 'Quicksand', 'Rattlesnake', 'Stalactite', 'Thunderstorm', 'Underworld', 'Vortex', 'Wombat',
    'X-ray', 'Yellowstone', 'Zephyr', 'Amethyst', 'Banyan', 'Cascade', 'Dragonfruit', 'Eruption', 'Fjord', 'Glacier',
    'Hummingbird', 'Icicle', 'Jasmine', 'Kelp', 'Lynx', 'Mimosa', 'Nightingale', 'Opal', 'Penguin', 'Quartz',
    'Rainforest', 'Sandstorm', 'Tornado', 'Ultramarine', 'Volcano', 'Whisper', 'Xenolith', 'Yew', 'Zebra',
    'Aurora', 'Balloon', 'Crescent', 'Dolphin', 'Empire', 'Feather', 'Galaxy', 'Hurricane', 'Igloo', 'Jungle',
    'Kite', 'Lighthouse', 'Mermaid', 'Nebula', 'Ocelot', 'Pegasus', 'Quicksand', 'Rattlesnake', 'Stalactite', 'Thunderstorm',
    'Underworld', 'Vortex', 'Wombat', 'X-ray', 'Yellowstone', 'Zephyr', 'Amethyst', 'Banyan', 'Cascade', 'Dragonfruit',
    'Eruption', 'Fjord', 'Glacier', 'Hummingbird', 'Icicle', 'Jasmine', 'Kelp', 'Lynx', 'Mimosa', 'Nightingale',
    'Opal', 'Penguin', 'Quartz', 'Rainforest', 'Sandstorm', 'Tornado', 'Ultramarine', 'Volcano', 'Whisper', 'Xenolith',
    'Yew', 'Zebra', 'Asteroid', 'Bamboo', 'Caribou', 'Dandelion', 'Eagle', 'Flamethrower', 'Gargantuan', 'Holograph',
    'Indigo', 'Jackal', 'Kookaburra', 'Lemur', 'Molecule', 'Nectarine', 'Osprey', 'Pineapple', 'Quartzite', 'Ravine',
    'Sundial', 'Teardrop', 'Uranium', 'Velvet', 'Warrior', 'Xenophobe', 'Yew', 'Zircon', 'Antelope', 'Bison',
    'Cobra', 'Desert', 'Echidna', 'Falconry', 'Garnet', 'Hippogriff', 'Inchworm', 'Jellyfish', 'Koala', 'Labrador',
    'Mantis', 'Narwhal', 'Orchid', 'Panther', 'Quartz', 'Raccoon', 'Starfish', 'Toucan', 'Unicorn', 'Vulture',
    'Wombat', 'Xenon', 'Yak', 'Zealot', 'Aardvark', 'Baboon', 'Cheetah', 'Dromedary', 'Eel', 'Fox',
    'Gibbon', 'Hamster', 'Iguana', 'Jackrabbit', 'Kingfisher', 'Lynx', 'Manatee', 'Nightingale', 'Owl', 'Platypus',
    'Quetzal', 'Rhinoceros', 'Salamander', 'Tortoise', 'Uakari', 'Vicuna', 'Walrus', 'Xerus', 'Yakut', 'Zebra',
    'Amaranth', 'Bracken', 'Cypress', 'Dahlia', 'Edelweiss', 'Fern', 'Gardenia', 'Honeysuckle', 'Iris', 'Jasmine',
    'Kudzu', 'Lavender', 'Magnolia', 'Narcissus', 'Orchid', 'Poppy', 'Quince', 'Rose', 'Sunflower', 'Tulip',
    'Umbrella', 'Violet', 'Waterlily', 'Xerophyte', 'Yucca', 'Zinnia', 'Acacia', 'Bluebell', 'Camellia', 'Daisy',
    'Eucalyptus', 'Ficus', 'Geranium', 'Hibiscus', 'Impatiens', 'Juniper', 'Kalanchoe', 'Lilac', 'Mimosa', 'Nandina',
    'Oleander', 'Petunia', 'Quercus', 'Redwood', 'Sagebrush', 'Thyme', 'Umbrella', 'Verbena', 'Willow', 'Xylosma',
    'Yarrow', 'Zelkova'
]
